#### cadastro de animal
POST http://localhost:3000/animal
Content-Type: application/json

{
    "nome": "Gustavo Henrique Andrade",
    "idade": 4,
    "tipo": "Macaco",
    "sexo": "Macho",
    "data_resgate": "2025-11-03T00:00:00.000Z",
    "canil": "Selva Amazônica"
}

#### listagem de animais
GET http://localhost:3000/animal


#### atualização de animal
PUT http://localhost:3000/animal/1
Content-Type: application/json

{
    "nome": "Rex",
    "idade": 5,
    "tipo": "Cachorro",
    "sexo": "Macho",
    "data_resgate": "2025-11-06T00:00:00.000Z",
    "canil": "Canil 1"
}

#### exclusão de animal
DELETE http://localhost:3000/animal/4